name: Build and Push Docker Images

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and Push Docker images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 19

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build
      
      - name: Build and Push Docker Images
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          IMAGE_NAME="taeng0204/dashboard"
          docker build -t $IMAGE_NAME .
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          docker push $IMAGE_NAME
